baseURL = 'http://rShar01.github.io'
languageCode = 'en-us'
title = 'Ryan Shar'
theme = 'm10c'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
    
[params]
  author = "Ryan Shar"
  description1 = "Undergraduate @ University of British Columbia"
  description2 = "Interested in Causal Inference and Reinforcement Learning"
  menu_item_separator = " - "